# Header
menu:
  Home: /
  About Us: /about/
  Our Music: /music/
  Gallery: /gallery/
  Events: /events/
  Blog: /blog/
  Contact Us: /contact/
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right

widgets:
- category
# - tag
# - tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-89573348-1
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
